// Mocks generated by Mockito 5.4.4 from annotations
// in task_6/test/helper/helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:convert' as _i14;
import 'dart:typed_data' as _i16;

import 'package:bloc/bloc.dart' as _i26;
import 'package:dartz/dartz.dart' as _i4;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:shared_preferences/shared_preferences.dart' as _i23;
import 'package:task_6/core/error/faliure.dart' as _i18;
import 'package:task_6/core/Network/networl_info.dart' as _i22;
import 'package:task_6/Product/data/dataSource/local_product_source.dart'
    as _i21;
import 'package:task_6/Product/data/dataSource/remote_product_source.dart'
    as _i17;
import 'package:task_6/Product/data/model/product_model.dart' as _i3;
import 'package:task_6/Product/data/model/ptoduct_to_save.dart' as _i19;
import 'package:task_6/Product/domain/entitiy/product_entities.dart' as _i20;
import 'package:task_6/Product/domain/repository/product_repository.dart'
    as _i5;
import 'package:task_6/Product/domain/usecase/add_product_usecase.dart' as _i10;
import 'package:task_6/Product/domain/usecase/delete_product_usecase.dart'
    as _i9;
import 'package:task_6/Product/domain/usecase/get_all_products.dart' as _i6;
import 'package:task_6/Product/domain/usecase/get_product_by_id.dart' as _i7;
import 'package:task_6/Product/domain/usecase/update_product_usecase.dart'
    as _i8;
import 'package:task_6/Product/presentation/bloc/product_bloc.dart' as _i24;
import 'package:task_6/Product/presentation/bloc/product_event.dart' as _i25;
import 'package:task_6/Product/presentation/bloc/product_state.dart' as _i11;
import 'package:task_6/User/Domain/Entities/user_entities.dart' as _i28;
import 'package:task_6/User/Domain/Repository/user_repository.dart' as _i12;
import 'package:task_6/User/Domain/Usecases/login_usecase.dart' as _i27;
import 'package:task_6/User/Domain/Usecases/signIn_usecase.dart' as _i29;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_1 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductsModel_2 extends _i1.SmartFake implements _i3.ProductsModel {
  _FakeProductsModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductRepository_4 extends _i1.SmartFake
    implements _i5.ProductRepository {
  _FakeProductRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAllProductUsecase_5 extends _i1.SmartFake
    implements _i6.AllProductUsecase {
  _FakeAllProductUsecase_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeShowProductById_6 extends _i1.SmartFake
    implements _i7.ShowProductById {
  _FakeShowProductById_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateProductUsecase_7 extends _i1.SmartFake
    implements _i8.UpdateProductUsecase {
  _FakeUpdateProductUsecase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteProductbyidUsecase_8 extends _i1.SmartFake
    implements _i9.DeleteProductbyidUsecase {
  _FakeDeleteProductbyidUsecase_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddProductUsecase_9 extends _i1.SmartFake
    implements _i10.AddProductUsecase {
  _FakeAddProductUsecase_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductState_10 extends _i1.SmartFake implements _i11.ProductState {
  _FakeProductState_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRepository_11 extends _i1.SmartFake
    implements _i12.UserRepository {
  _FakeUserRepository_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i13.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i13.Future<_i2.Response>);

  @override
  _i13.Future<_i2.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i13.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i13.Future<_i2.Response>);

  @override
  _i13.Future<_i2.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i13.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i13.Future<_i2.Response>);

  @override
  _i13.Future<_i2.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i13.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i13.Future<_i2.Response>);

  @override
  _i13.Future<_i2.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i13.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i13.Future<_i2.Response>);

  @override
  _i13.Future<_i2.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i14.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i13.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i13.Future<_i2.Response>);

  @override
  _i13.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i13.Future<String>.value(_i15.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i13.Future<String>);

  @override
  _i13.Future<_i16.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i13.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
      ) as _i13.Future<_i16.Uint8List>);

  @override
  _i13.Future<_i2.StreamedResponse> send(_i2.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i13.Future<_i2.StreamedResponse>.value(_FakeStreamedResponse_1(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i13.Future<_i2.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i17.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.ProductsModel> getProductById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i13.Future<_i3.ProductsModel>.value(_FakeProductsModel_2(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i13.Future<_i3.ProductsModel>);

  @override
  _i13.Future<_i4.Either<_i18.Failure, bool>> ProductAdd(
    _i19.SendProduct? product,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #ProductAdd,
          [
            product,
            token,
          ],
        ),
        returnValue: _i13.Future<_i4.Either<_i18.Failure, bool>>.value(
            _FakeEither_3<_i18.Failure, bool>(
          this,
          Invocation.method(
            #ProductAdd,
            [
              product,
              token,
            ],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, bool>>);

  @override
  _i13.Future<_i4.Either<_i18.Failure, bool>> ProductDelete(
    String? productId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #ProductDelete,
          [
            productId,
            token,
          ],
        ),
        returnValue: _i13.Future<_i4.Either<_i18.Failure, bool>>.value(
            _FakeEither_3<_i18.Failure, bool>(
          this,
          Invocation.method(
            #ProductDelete,
            [
              productId,
              token,
            ],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, bool>>);

  @override
  _i13.Future<_i4.Either<_i18.Failure, bool>> ProductUpdate(
    String? productId,
    _i20.ProductEnities? product,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #ProductUpdate,
          [
            productId,
            product,
            token,
          ],
        ),
        returnValue: _i13.Future<_i4.Either<_i18.Failure, bool>>.value(
            _FakeEither_3<_i18.Failure, bool>(
          this,
          Invocation.method(
            #ProductUpdate,
            [
              productId,
              product,
              token,
            ],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, bool>>);

  @override
  _i13.Future<_i4.Either<_i18.Failure, List<_i3.ProductsModel>>> getAllProduct(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProduct,
          [token],
        ),
        returnValue: _i13
            .Future<_i4.Either<_i18.Failure, List<_i3.ProductsModel>>>.value(
            _FakeEither_3<_i18.Failure, List<_i3.ProductsModel>>(
          this,
          Invocation.method(
            #getAllProduct,
            [token],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, List<_i3.ProductsModel>>>);
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i21.ProductLocalDataSource {
  MockProductLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i3.ProductsModel>> getStoredProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStoredProducts,
          [],
        ),
        returnValue:
            _i13.Future<List<_i3.ProductsModel>>.value(<_i3.ProductsModel>[]),
      ) as _i13.Future<List<_i3.ProductsModel>>);

  @override
  _i13.Future<bool> storeProduct(List<_i3.ProductsModel>? productToStore) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeProduct,
          [productToStore],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> deleteProduct(String? Id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [Id],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<_i3.ProductsModel> getSingleProduct(String? Id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSingleProduct,
          [Id],
        ),
        returnValue: _i13.Future<_i3.ProductsModel>.value(_FakeProductsModel_2(
          this,
          Invocation.method(
            #getSingleProduct,
            [Id],
          ),
        )),
      ) as _i13.Future<_i3.ProductsModel>);

  @override
  _i13.Future<bool> storeSingleProduct(_i3.ProductsModel? updatedProduct) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSingleProduct,
          [updatedProduct],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> clearToken() => (super.noSuchMethod(
        Invocation.method(
          #clearToken,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i13.Future<String?>.value(),
      ) as _i13.Future<String?>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i22.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i23.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i13.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [AllProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAllProductUsecase extends _i1.Mock implements _i6.AllProductUsecase {
  MockAllProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);

  @override
  _i13.Future<_i4.Either<_i18.Failure, List<_i20.ProductEnities>>>
      call_AllProducts() => (super.noSuchMethod(
            Invocation.method(
              #call_AllProducts,
              [],
            ),
            returnValue: _i13.Future<
                    _i4.Either<_i18.Failure, List<_i20.ProductEnities>>>.value(
                _FakeEither_3<_i18.Failure, List<_i20.ProductEnities>>(
              this,
              Invocation.method(
                #call_AllProducts,
                [],
              ),
            )),
          ) as _i13
              .Future<_i4.Either<_i18.Failure, List<_i20.ProductEnities>>>);
}

/// A class which mocks [ShowProductById].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowProductById extends _i1.Mock implements _i7.ShowProductById {
  MockShowProductById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  _i13.Future<_i4.Either<_i18.Failure, _i20.ProductEnities>> call_show(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call_show,
          [productId],
        ),
        returnValue:
            _i13.Future<_i4.Either<_i18.Failure, _i20.ProductEnities>>.value(
                _FakeEither_3<_i18.Failure, _i20.ProductEnities>(
          this,
          Invocation.method(
            #call_show,
            [productId],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, _i20.ProductEnities>>);
}

/// A class which mocks [UpdateProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProductUsecase extends _i1.Mock
    implements _i8.UpdateProductUsecase {
  MockUpdateProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  _i13.Future<_i4.Either<_i18.Failure, bool>> call_update(
    String? productId,
    _i20.ProductEnities? product,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call_update,
          [
            productId,
            product,
          ],
        ),
        returnValue: _i13.Future<_i4.Either<_i18.Failure, bool>>.value(
            _FakeEither_3<_i18.Failure, bool>(
          this,
          Invocation.method(
            #call_update,
            [
              productId,
              product,
            ],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, bool>>);
}

/// A class which mocks [DeleteProductbyidUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProductbyidUsecase extends _i1.Mock
    implements _i9.DeleteProductbyidUsecase {
  MockDeleteProductbyidUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);

  @override
  _i13.Future<_i4.Either<_i18.Failure, bool>> call_delete(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call_delete,
          [productId],
        ),
        returnValue: _i13.Future<_i4.Either<_i18.Failure, bool>>.value(
            _FakeEither_3<_i18.Failure, bool>(
          this,
          Invocation.method(
            #call_delete,
            [productId],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, bool>>);
}

/// A class which mocks [AddProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddProductUsecase extends _i1.Mock implements _i10.AddProductUsecase {
  MockAddProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ProductRepository get productRepository => (super.noSuchMethod(
        Invocation.getter(#productRepository),
        returnValue: _FakeProductRepository_4(
          this,
          Invocation.getter(#productRepository),
        ),
      ) as _i5.ProductRepository);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  _i13.Future<_i4.Either<_i18.Failure, bool>> call_add(
          _i19.SendProduct? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #call_add,
          [product],
        ),
        returnValue: _i13.Future<_i4.Either<_i18.Failure, bool>>.value(
            _FakeEither_3<_i18.Failure, bool>(
          this,
          Invocation.method(
            #call_add,
            [product],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, bool>>);
}

/// A class which mocks [ProductBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductBloc extends _i1.Mock implements _i24.ProductBloc {
  MockProductBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AllProductUsecase get getAllProductsUseCase => (super.noSuchMethod(
        Invocation.getter(#getAllProductsUseCase),
        returnValue: _FakeAllProductUsecase_5(
          this,
          Invocation.getter(#getAllProductsUseCase),
        ),
      ) as _i6.AllProductUsecase);

  @override
  _i7.ShowProductById get getProductByIdUseCase => (super.noSuchMethod(
        Invocation.getter(#getProductByIdUseCase),
        returnValue: _FakeShowProductById_6(
          this,
          Invocation.getter(#getProductByIdUseCase),
        ),
      ) as _i7.ShowProductById);

  @override
  _i8.UpdateProductUsecase get updateProductUseCase => (super.noSuchMethod(
        Invocation.getter(#updateProductUseCase),
        returnValue: _FakeUpdateProductUsecase_7(
          this,
          Invocation.getter(#updateProductUseCase),
        ),
      ) as _i8.UpdateProductUsecase);

  @override
  _i9.DeleteProductbyidUsecase get deleteProductUseCase => (super.noSuchMethod(
        Invocation.getter(#deleteProductUseCase),
        returnValue: _FakeDeleteProductbyidUsecase_8(
          this,
          Invocation.getter(#deleteProductUseCase),
        ),
      ) as _i9.DeleteProductbyidUsecase);

  @override
  _i10.AddProductUsecase get addProductUseCase => (super.noSuchMethod(
        Invocation.getter(#addProductUseCase),
        returnValue: _FakeAddProductUsecase_9(
          this,
          Invocation.getter(#addProductUseCase),
        ),
      ) as _i10.AddProductUsecase);

  @override
  _i11.ProductState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeProductState_10(
          this,
          Invocation.getter(#state),
        ),
      ) as _i11.ProductState);

  @override
  _i13.Stream<_i11.ProductState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i13.Stream<_i11.ProductState>.empty(),
      ) as _i13.Stream<_i11.ProductState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i25.ProductEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i25.ProductEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i11.ProductState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i25.ProductEvent>(
    _i26.EventHandler<E, _i11.ProductState>? handler, {
    _i26.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i26.Transition<_i25.ProductEvent, _i11.ProductState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  void onChange(_i26.Change<_i11.ProductState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i27.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.UserRepository);

  @override
  _i13.Future<_i4.Either<_i18.Failure, bool>> call(_i28.UserEnities? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [user],
        ),
        returnValue: _i13.Future<_i4.Either<_i18.Failure, bool>>.value(
            _FakeEither_3<_i18.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [user],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, bool>>);
}

/// A class which mocks [SignUpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUseCase extends _i1.Mock implements _i29.SignUpUseCase {
  MockSignUpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_11(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.UserRepository);

  @override
  _i13.Future<_i4.Either<_i18.Failure, bool>> call(_i28.UserEnities? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [user],
        ),
        returnValue: _i13.Future<_i4.Either<_i18.Failure, bool>>.value(
            _FakeEither_3<_i18.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [user],
          ),
        )),
      ) as _i13.Future<_i4.Either<_i18.Failure, bool>>);
}
